title: Dr
name: Nur
surname: Ozyilmaz
fulltitle: Dr Nur Ozyilmaz
appname: DrNur
email: contact@drnur.co.uk
tel: 07568 265217
address: "58 South Molton Street<br>London<br>W1K 5SL"
map: "https://goo.gl/maps/7YkcAt5nm9z"
description: Dr Nur Ozyilmaz is an experienced, UK trained, integrative health consultant who has worked in some of the most renowned London hospitals, including Kings College Hospital, Great Ormond Street, and St Thomas’ Hospital.
jobtitle: Integrative Health Consultant
qualifications: CONSULTANT MD MRCPCH
qualification: MD
url: "https://drnur.co.uk"
image: "https://drnur.co.uk/assets/img/nur.jpg"
facebook: "https://www.facebook.com/drnurozyilmaz/"
contactaction: "https://postman.etilia.com/d17c7c2c-5259-4318-8ce9-1c2f2fa62d35"
practice: PRACTICE IN LONDON, UK
thanks: THANKS FOR VISITING
speciality:
  - title: Multi-disciplinary
    description: Developed a multi-disciplinary, holistic approach that uses Western medicine, traditional and laser acupuncture, functional medicine, advanced bioregulatory therapy, nutritional and herbal remedies
  - title: Nutrition
    description: Carries out detailed individual nutritional assessments, advices and supports her patients in their transition to a more balanced and tailored nutritional plan
